# Generated by Django 5.1.7 on 2025-04-15 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('Sedán', 'Sedán'), ('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Pickup', 'Pickup'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Otro', 'Otro')], default='SUV', max_length=20, verbose_name='Tipo de carrocería'),
        ),
        migrations.AddField(
            model_name='car',
            name='doors',
            field=models.PositiveIntegerField(default=4, verbose_name='Puertas'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Eléctrico', 'Eléctrico'), ('Gasolina', 'Gasolina'), ('Diesel', 'Diesel'), ('Híbrido', 'Híbrido')], default='Eléctrico', max_length=20, verbose_name='Tipo de combustible'),
        ),
        migrations.AddField(
            model_name='car',
            name='kilometers',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilómetros'),
        ),
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.CharField(default='Sin especificar', max_length=100, verbose_name='Lugar de publicación'),
        ),
        migrations.AddField(
            model_name='car',
            name='plate',
            field=models.CharField(default='AAA000', max_length=6, validators=[django.core.validators.RegexValidator(message='La placa debe tener el formato ABC123 (3 letras + 3 números)', regex='^[A-Z]{3}\\d{3}$')], verbose_name='Placa'),
        ),
        migrations.AddField(
            model_name='car',
            name='steering',
            field=models.CharField(choices=[('Hidráulica', 'Hidráulica'), ('Eléctrica', 'Eléctrica'), ('Mecánica', 'Mecánica')], default='Eléctrica', max_length=20, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='car',
            name='traction_control',
            field=models.CharField(choices=[('Delantera', 'Delantera'), ('Trasera', 'Trasera'), ('4x4', '4x4'), ('AWD', 'AWD')], default='Delantera', max_length=20, verbose_name='Control de tracción'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Automática', 'Automática'), ('Manual', 'Manual')], default='Automática', max_length=20, verbose_name='Transmisión'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('Tesla', 'Tesla'), ('Nissan', 'Nissan'), ('BMW', 'BMW'), ('Audi', 'Audi'), ('Hyundai', 'Hyundai'), ('Kia', 'Kia'), ('Otros', 'Otros')], default='Otros', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(2010), django.core.validators.MaxValueValidator(2026)]),
        ),
    ]
