# Generated by Django 5.1.7 on 2025-04-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_body_type_car_doors_car_fuel_type_car_kilometers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('Renault', 'Renault'), ('Toyota', 'Toyota'), ('Chevrolet', 'Chevrolet'), ('Mazda', 'Mazda'), ('Kia', 'Kia'), ('Hyundai', 'Hyundai'), ('Nissan', 'Nissan'), ('Suzuki', 'Suzuki'), ('Volkswagen', 'Volkswagen'), ('Ford', 'Ford'), ('BYD', 'BYD'), ('Zhidou', 'Zhidou'), ('Mini', 'Mini'), ('BMW', 'BMW'), ('Tesla', 'Tesla'), ('Audi', 'Audi'), ('Otros', 'Otros')], default='Otros', max_length=50),
        ),
    ]
