# Generated by Django 5.1.7 on 2025-04-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.JSONField(default=list),
        ),
    ]
