# Generated by Django 5.1.7 on 2025-04-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
